{
 "title": "Kiel - Air Quality",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "kiel_air_quality_sensor_ids",
    "label": "Sensor wählen:",
    "query": "SELECT DISTINCT entity_id FROM mtsmartmaas001.etairqualityobserved WHERE WITHIN(\"location_centroid\", 'POLYGON ((9.927864074707031 54.24817702140307, 10.323028564453125 54.24817702140307, 10.323028564453125 54.43530732913595, 9.927864074707031 54.43530732913595, 9.927864074707031 54.24817702140307))');"
   }
  ]
 },
 "panels": [
  {
   "type": "pierosavi-imageit-panel",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT\n  $__time(time_column),\n  value1\nFROM\n  metric_table\nWHERE\n  $__timeFilter(time_column)\n"
    }
   ]
  },
  {
   "type": "pierosavi-imageit-panel",
   "gridPos": { "h": 3, "w": 2, "x": 2, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT\n  $__time(time_column),\n  value1\nFROM\n  metric_table\nWHERE\n  $__timeFilter(time_column)\n"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 15, "x": 4, "y": 0 },
   "content": "<h1 style=\"text-align: center; font-size: 6em;\">Luftqualität Kiel</h1>",
   "targets": [
    {
     "rawSql": "SELECT\n  $__time(time_column),\n  value1\nFROM\n  metric_table\nWHERE\n  $__timeFilter(time_column)\n"
    }
   ]
  },
  {
   "type": "grafana-clock-panel",
   "gridPos": { "h": 4, "w": 5, "x": 19, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT\n  $__time(time_column),\n  value1\nFROM\n  metric_table\nWHERE\n  $__timeFilter(time_column)\n"
    }
   ]
  },
  {
   "title": "Informationen",
   "type": "text",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 3 },
   "content": "Verbindlich einzuhaltener Jahresmittelwert für Feinstaub der Kategorie PM2,5 beträgt 25 µg/m³. Für PM10 beträgt die Grenze 40 µg/m³.\n",
   "targets": [
    {
     "select": [
      [
       { "params": [ "value" ], "type": "column" }
      ]
     ],
     "where": [
      {
       "name": "$__timeFilter",
       "params": [],
       "type": "macro"
      }
     ]
    }
   ]
  },
  {
   "title": "Gemessene Feinstaubwerte der Kategorie PM2,5 (µg/m³) - Aktueller Monat",
   "type": "graph",
   "description": "Messungen von Feinstaub der Partikelgröße PM2,5 (Partikel mit einem aerodynamischen Durchmesser von <= 2,5 Mikrometer)",
   "gridPos": { "h": 10, "w": 13, "x": 6, "y": 3 },
   "yaxes": [
    { "format": "short", "label": "µg/m³" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  time_index AS \"time\",\n  entity_id AS metric,\n  pm25 AS \"PM2.5\"\nFROM mtsmartmaas001.etairqualityobserved\nWHERE\n  entity_id IN ($kiel_air_quality_sensor_ids) \n  AND WITHIN(\"location_centroid\", 'POLYGON ((9.927864074707031 54.24817702140307, 10.323028564453125 54.24817702140307, 10.323028564453125 54.43530732913595, 9.927864074707031 54.43530732913595, 9.927864074707031 54.24817702140307))') \n  AND extract(month from \"time_index\") = extract(month from CURRENT_TIMESTAMP) \nORDER BY 1,2"
    }
   ]
  },
  {
   "title": "Überwachung der Jahresmittelwerte für PM2,5",
   "type": "yesoreyeram-boomtable-panel",
   "description": "Für PM2,5 gilt seit 2008 europaweit ein Zielwert von 25 µg/m³ im Jahresmittel, der bereits seit dem 1. Januar 2010 eingehalten werden soll. Seit 1. Januar 2015 ist dieser Wert verbindlich einzuhalten.",
   "gridPos": { "h": 9, "w": 5, "x": 19, "y": 4 },
   "targets": [
    {
     "rawSql": "SELECT\n  time_index AS \"time\",\n  entity_id AS metric,\n  pm25 AS \"PM2.5\"\nFROM mtsmartmaas001.etairqualityobserved\nWHERE\n  entity_id IN ($kiel_air_quality_sensor_ids)\n  AND WITHIN(\"location_centroid\", 'POLYGON ((9.927864074707031 54.24817702140307, 10.323028564453125 54.24817702140307, 10.323028564453125 54.43530732913595, 9.927864074707031 54.43530732913595, 9.927864074707031 54.24817702140307))') \n  AND extract(year from \"time_index\") = extract(year from CURRENT_TIMESTAMP) \nORDER BY 1,2"
    }
   ]
  },
  {
   "title": "Höchster Feinstaubwert des Tages für PM2,5 (µg/m³)",
   "type": "farski-blendstat-panel",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 6 },
   "format": "conμgm3",
   "valueName": "avg",
   "targets": [
    {
     "aggregation": "Last",
     "decimals": 2,
     "displayAliasType": "Warning / Critical",
     "displayType": "Regular",
     "displayValueWithAlias": "Never",
     "rawSql": "SELECT \"pm25\" \r\nFROM \"mtsmartmaas001\".\"etairqualityobserved\" \r\nWHERE WITHIN(\"location_centroid\", 'POLYGON ((9.927864074707031 54.24817702140307, 10.323028564453125 54.24817702140307, 10.323028564453125 54.43530732913595, 9.927864074707031 54.43530732913595, 9.927864074707031 54.24817702140307))') \r\nAND extract(day from \"time_index\") = extract(day from CURRENT_TIMESTAMP) \r\nAND \"pm25\" IS NOT NULL \r\nORDER BY \"pm25\" DESC limit 1;",
     "units": "none",
     "valueHandler": "Number Threshold"
    }
   ]
  },
  {
   "title": "Aktuelle Feinstaubmesswerte für PM2,5 (µg/m³)",
   "type": "grafana-worldmap-panel",
   "description": "Der Kartenausschnitt zeigt die heutigen, zuletzt an unterschiedlichen Standorten im Raum Kiel gemessenen Feinstaubwerte der Kategorie PM2,5.",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 13 },
   "valueName": "current",
   "targets": [
    {
     "groupByAliases": [ "type" ],
     "groupByColumns": [ "entity_type" ],
     "metricAggs": [
      { "alias": "id", "column": "entity_id", "type": "raw" },
      { "alias": "value", "column": "availablespotnumber", "type": "raw" },
      { "alias": "geojson", "column": "location", "type": "raw" },
      { "alias": "created_at", "column": "time_index", "type": "raw" }
     ],
     "rawSql": "SELECT\r\n  \"entity_id\", \r\n  LATITUDE(\"location_centroid\") AS \"geo_lat\", LONGITUDE(\"location_centroid\") AS \"geo_long\", \r\n  \"pm25\",\r\n  MAX(\"time_index\") as \"last_measure_time\" \r\nFROM mtsmartmaas001.etairqualityobserved\r\nWHERE \r\n  WITHIN(\"location_centroid\", 'POLYGON ((9.927864074707031 54.24817702140307, 10.323028564453125 54.24817702140307, 10.323028564453125 54.43530732913595, 9.927864074707031 54.43530732913595, 9.927864074707031 54.24817702140307))') \r\n  AND extract(day from \"time_index\") = extract(day from CURRENT_TIMESTAMP) \r\n  AND \"pm25\" IS NOT NULL \r\nGroup BY 1, 2, 3, 4;"
    }
   ]
  },
  {
   "title": "Gemessene Feinstaubwerte der Kategorie PM10 (µg/m³) - Aktueller Monat",
   "type": "graph",
   "description": "Messungen von Feinstaub der Partikelgröße PM10 (Partikel mit einem aerodynamischen Durchmesser von <= 10 Mikrometer)",
   "gridPos": { "h": 9, "w": 13, "x": 6, "y": 13 },
   "yaxes": [
    { "format": "short", "label": "µg/m³" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  time_index AS \"time\",\n  entity_id AS metric,\n  pm10 AS \"PM10\"\nFROM mtsmartmaas001.etairqualityobserved\nWHERE\n  entity_id IN ($kiel_air_quality_sensor_ids) \n  AND WITHIN(\"location_centroid\", 'POLYGON ((9.927864074707031 54.24817702140307, 10.323028564453125 54.24817702140307, 10.323028564453125 54.43530732913595, 9.927864074707031 54.43530732913595, 9.927864074707031 54.24817702140307))') \n  AND extract(month from \"time_index\") = extract(month from CURRENT_TIMESTAMP) \nORDER BY 1,2"
    }
   ]
  },
  {
   "title": "Überwachung der Jahresmittelwerte für PM10",
   "type": "yesoreyeram-boomtable-panel",
   "description": "Zum Schutz der menschlichen Gesundheit gelten seit dem 1. Januar 2005 europaweit Grenzwerte für die Feinstaubfraktion PM10. Der zulässige Jahresmittelwert beträgt 40 µg/m³.",
   "gridPos": { "h": 9, "w": 5, "x": 19, "y": 13 },
   "targets": [
    {
     "rawSql": "SELECT\n  time_index AS \"time\",\n  entity_id AS metric,\n  pm10 AS \"PM10\"\nFROM mtsmartmaas001.etairqualityobserved\nWHERE\n  entity_id IN ($kiel_air_quality_sensor_ids)\n  AND WITHIN(\"location_centroid\", 'POLYGON ((9.927864074707031 54.24817702140307, 10.323028564453125 54.24817702140307, 10.323028564453125 54.43530732913595, 9.927864074707031 54.43530732913595, 9.927864074707031 54.24817702140307))') \n  AND extract(year from \"time_index\") = extract(year from CURRENT_TIMESTAMP) \nORDER BY 1,2"
    }
   ]
  },
  {
   "title": "Visualisierte Luftdaten von augewählten Sensoren in Deutschland via Wirecloud Widget Mashup",
   "type": "ryantxu-ajax-panel",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 22 },
   "targets": [
    {
     "rawSql": "SELECT\n  $__time(time_column),\n  value1\nFROM\n  metric_table\nWHERE\n  $__timeFilter(time_column)\n"
    }
   ]
  }
 ]
}