{
 "title": "Kiel - Parking",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "kiel_parking_sensor_ids",
    "label": "Sensor wählen:",
    "query": "SELECT DISTINCT entity_id FROM mtsmartmaas001.etparkingspot WHERE entity_id LIKE '%-MS';"
   }
  ]
 },
 "panels": [
  {
   "type": "pierosavi-imageit-panel",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT\n  $__time(time_column),\n  value1\nFROM\n  metric_table\nWHERE\n  $__timeFilter(time_column)\n"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 11, "x": 2, "y": 0 },
   "content": "<h1 style=\"text-align: center; font-size: 6em;\">Parkplatzmonitor Kiel</h1>",
   "targets": [
    {
     "rawSql": "SELECT\n  $__time(time_column),\n  value1\nFROM\n  metric_table\nWHERE\n  $__timeFilter(time_column)\n"
    }
   ]
  },
  {
   "type": "ryantxu-ajax-panel",
   "gridPos": { "h": 4, "w": 6, "x": 13, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT\n  $__time(time_column),\n  value1\nFROM\n  metric_table\nWHERE\n  $__timeFilter(time_column)\n"
    }
   ]
  },
  {
   "type": "grafana-clock-panel",
   "gridPos": { "h": 4, "w": 5, "x": 19, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT\n  $__time(time_column),\n  value1\nFROM\n  metric_table\nWHERE\n  $__timeFilter(time_column)\n"
    }
   ]
  },
  {
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 3 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "rawSql": "SELECT COUNT(DISTINCT \"entity_id\") AS \"total_count\" \r\nFROM \"mtsmartmaas001\".\"etparkingspot\" WHERE \"entity_id\" LIKE '%-MS';"
    }
   ]
  },
  {
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 5, "x": 3, "y": 3 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "rawSql": "SELECT \"status\", (CASE WHEN \"status\" = 'free' THEN 0 WHEN \"status\" = 'occupied' THEN 1 END) AS \"num_status\", COUNT(\"status\") AS \"status_count\", \"total_count\" \r\nFROM \"mtsmartmaas001\".\"etparkingspot\" \r\n  JOIN (SELECT \"entity_id\" AS \"eId\", MAX(\"time_index\") AS \"last_update\" \r\n        FROM \"mtsmartmaas001\".\"etparkingspot\" \r\n        WHERE \"entity_id\" LIKE '%-MS' \r\n        GROUP BY \"entity_id\") SUB \r\n  ON (\"entity_id\" = \"eId\" AND \"time_index\" = \"last_update\") \r\n  JOIN (SELECT COUNT(DISTINCT \"entity_id\") AS \"total_count\" \r\n        FROM \"mtsmartmaas001\".\"etparkingspot\" WHERE \"entity_id\" LIKE '%-MS') SUB2 \r\n  ON (true) \r\nWHERE \"status\" = 'free' \r\nAND \"entity_id\" LIKE '%-MS' \r\nGROUP BY \"status\", \"total_count\";"
    }
   ]
  },
  {
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 5, "x": 8, "y": 3 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "rawSql": "SELECT \"status\", (CASE WHEN \"status\" = 'free' THEN 0 WHEN \"status\" = 'occupied' THEN 1 END) AS \"num_status\", COUNT(\"status\") AS \"status_count\", \"total_count\" \r\nFROM \"mtsmartmaas001\".\"etparkingspot\" \r\n  JOIN (SELECT \"entity_id\" AS \"eId\", MAX(\"time_index\") AS \"last_update\" \r\n        FROM \"mtsmartmaas001\".\"etparkingspot\" \r\n        WHERE \"entity_id\" LIKE '%-MS' \r\n        GROUP BY \"entity_id\") SUB \r\n  ON (\"entity_id\" = \"eId\" AND \"time_index\" = \"last_update\") \r\n  JOIN (SELECT COUNT(DISTINCT \"entity_id\") AS \"total_count\" \r\n        FROM \"mtsmartmaas001\".\"etparkingspot\" WHERE \"entity_id\" LIKE '%-MS') SUB2 \r\n  ON (true) \r\nWHERE \"status\" = 'occupied' \r\nAND \"entity_id\" LIKE '%-MS' \r\nGROUP BY \"status\", \"total_count\";"
    }
   ]
  },
  {
   "title": "Informationen",
   "type": "text",
   "gridPos": { "h": 4, "w": 11, "x": 13, "y": 4 },
   "content": "Mithilfe einer neuen Sensorentechnik will die Stadt Kiel die Suche nach einem Parkplatz vereinfachen. Im Rahmen eines Pilotprojekts gibt es die ersten Sensoren schon auf 17 Parkplätzen entlang der Kiellinie. Sie verstecken sich in kleinen, schwarzen Hubbeln und funken die Information, ob ein Parkplatz frei oder besetzt ist, in regelmäßigen Zeitabständen an Rechner bei den Stadtwerken.\n\n",
   "targets": [
    {
     "select": [
      [
       { "params": [ "value" ], "type": "column" }
      ]
     ],
     "where": [
      {
       "name": "$__timeFilter",
       "params": [],
       "type": "macro"
      }
     ]
    }
   ]
  },
  {
   "title": "Aktueller Status der Parkplätze",
   "type": "snuids-trafficlights-panel",
   "gridPos": { "h": 11, "w": 13, "x": 0, "y": 6 },
   "targets": [
    {
     "groupByAliases": [ "type" ],
     "groupByColumns": [ "entity_type" ],
     "metricAggs": [
      { "alias": "id", "column": "entity_id", "type": "raw" },
      { "alias": "value", "column": "availablespotnumber", "type": "raw" },
      { "alias": "geojson", "column": "location", "type": "raw" },
      { "alias": "created_at", "column": "time_index", "type": "raw" }
     ],
     "rawSql": "SELECT \"entity_id\" AS \"metric\", (CASE WHEN \"status\" = 'free' THEN 0 WHEN \"status\" = 'occupied' THEN 1 END) AS \"num_status\", \"time_index\" AS \"time\" \r\nFROM \"mtsmartmaas001\".\"etparkingspot\" \r\n  JOIN (SELECT \"entity_id\" AS \"eId\", MAX(\"time_index\") AS \"last_update\" \r\n        FROM \"mtsmartmaas001\".\"etparkingspot\" \r\n        WHERE \"entity_id\" LIKE '%-MS' \r\n        GROUP BY \"entity_id\") SUB \r\n  ON (\"entity_id\" = \"eId\" AND \"time_index\" = \"last_update\") \r\nWHERE \"entity_id\" LIKE '%-MS' \r\nGROUP BY 1, 2, 3;"
    }
   ]
  },
  {
   "title": "Verlauf der gemeldeten Sensorzustände diese Woche",
   "type": "graph",
   "gridPos": { "h": 9, "w": 11, "x": 13, "y": 8 },
   "yaxes": [
    { "format": "short", "label": "frei / besetzt" }
   ],
   "targets": [
    {
     "aggregation": "Last",
     "decimals": 2,
     "displayAliasType": "Warning / Critical",
     "displayType": "Regular",
     "displayValueWithAlias": "Never",
     "groupByAliases": [ "type" ],
     "groupByColumns": [ "entity_type" ],
     "metricAggs": [
      { "alias": "id", "column": "entity_id", "type": "raw" },
      { "alias": "value", "column": "availablespotnumber", "type": "raw" },
      { "alias": "geojson", "column": "location", "type": "raw" },
      { "alias": "created_at", "column": "time_index", "type": "raw" }
     ],
     "rawSql": "SELECT\r\n  time_index AS \"time\",\r\n  entity_id AS metric,\r\n  (CASE WHEN \"status\" = 'free' THEN 0 WHEN \"status\" = 'occupied' THEN 1 END) AS \"status_value\" \r\nFROM \"mtsmartmaas001\".\"etparkingspot\" \r\nWHERE\r\n  entity_id IN ($kiel_parking_sensor_ids) \r\n  AND extract(week from \"time_index\") = extract(week from CURRENT_TIMESTAMP) \r\n  AND \"entity_id\" LIKE '%-MS' \r\nORDER BY 1,2;\r\n",
     "units": "none",
     "valueHandler": "Number Threshold"
    }
   ]
  },
  {
   "title": "Status-Visualisierung der Parkplatzsensoren an der Kiellinie via Wirecloud Widget Mashup",
   "type": "ryantxu-ajax-panel",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 17 },
   "targets": [
    {
     "rawSql": "SELECT\n  $__time(time_column),\n  value1\nFROM\n  metric_table\nWHERE\n  $__timeFilter(time_column)\n"
    }
   ]
  }
 ]
}