{
 "title": "Kiel - Weather",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "type": "pierosavi-imageit-panel",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT\n  $__time(time_column),\n  value1\nFROM\n  metric_table\nWHERE\n  $__timeFilter(time_column)\n"
    }
   ]
  },
  {
   "type": "pierosavi-imageit-panel",
   "gridPos": { "h": 3, "w": 2, "x": 2, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT\n  $__time(time_column),\n  value1\nFROM\n  metric_table\nWHERE\n  $__timeFilter(time_column)\n"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 12, "x": 4, "y": 0 },
   "content": "<h1 style=\"text-align: center; font-size: 6em;\">Wetter-Portal Kiel</h1>",
   "targets": [
    {
     "rawSql": "SELECT\n  $__time(time_column),\n  value1\nFROM\n  metric_table\nWHERE\n  $__timeFilter(time_column)\n"
    }
   ]
  },
  {
   "title": "Luftdruck (hPa) - Durchschnitt aktueller Monat",
   "type": "grafana-worldmap-panel",
   "description": "Der Kartenausschnitt zeigt den durchschnittlichen Luftdruck (hPa), der von mehreren Sensoren an unterschiedlichen Standorten im Raum Kiel im aktuellen Monat gemessen wurde.",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 0 },
   "valueName": "total",
   "targets": [
    {
     "groupByAliases": [ "type" ],
     "groupByColumns": [ "entity_type" ],
     "metricAggs": [
      { "alias": "id", "column": "entity_id", "type": "raw" },
      { "alias": "value", "column": "availablespotnumber", "type": "raw" },
      { "alias": "geojson", "column": "location", "type": "raw" },
      { "alias": "created_at", "column": "time_index", "type": "raw" }
     ],
     "rawSql": "SELECT \"entity_id\", LATITUDE(\"location_centroid\") AS \"geo_lat\", LONGITUDE(\"location_centroid\") AS \"geo_long\", AVG(\"atmosphericpressure\") AS \"avg_atmopressure\" \r\nFROM \"mtsmartmaas001\".\"etweatherobserved\" \r\nWHERE WITHIN(\"location_centroid\", 'POLYGON ((9.927864074707031 54.24817702140307, 10.323028564453125 54.24817702140307, 10.323028564453125 54.43530732913595, 9.927864074707031 54.43530732913595, 9.927864074707031 54.24817702140307))') \r\nAND extract(month from \"time_index\") = extract(month from CURRENT_TIMESTAMP) \r\nAND \"atmosphericpressure\" IS NOT NULL \r\nGROUP BY \"entity_id\", \"geo_lat\", \"geo_long\";"
    }
   ]
  },
  {
   "type": "grafana-clock-panel",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 3 },
   "targets": [
    {
     "rawSql": "SELECT\n  $__time(time_column),\n  value1\nFROM\n  metric_table\nWHERE\n  $__timeFilter(time_column)\n"
    }
   ]
  },
  {
   "title": "Live Cam - Kiel-Gaarden Turm",
   "type": "ryantxu-ajax-panel",
   "gridPos": { "h": 6, "w": 7, "x": 4, "y": 3 },
   "targets": [
    {
     "rawSql": "SELECT\n  $__time(time_column),\n  value1\nFROM\n  metric_table\nWHERE\n  $__timeFilter(time_column)\n"
    }
   ]
  },
  {
   "title": "Luftdruck (hPa) - Durchschnitt der letzten 7 Tage",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 5, "x": 11, "y": 3 },
   "format": "pressurehpa",
   "valueName": "avg",
   "targets": [
    {
     "rawSql": "SELECT AVG(\"atmosphericpressure\") AS \"avg_atmopressure\" \r\nFROM \"mtsmartmaas001\".\"etweatherobserved\" \r\nWHERE WITHIN(\"location_centroid\", 'POLYGON ((9.927864074707031 54.24817702140307, 10.323028564453125 54.24817702140307, 10.323028564453125 54.43530732913595, 9.927864074707031 54.43530732913595, 9.927864074707031 54.24817702140307))') \r\nAND \"time_index\" > DATE_FORMAT(CURRENT_TIMESTAMP - 1000*60*60*24*7) \r\nAND \"atmosphericpressure\" IS NOT NULL;"
    }
   ]
  },
  {
   "title": "Temperatur (°C) - Durchschnitt aktueller Monat",
   "type": "grafana-worldmap-panel",
   "description": "Der Kartenausschnitt zeigt die durchschnittliche Temperatur (°C), die von mehreren Sensoren an unterschiedlichen Standorten im Raum Kiel im aktuellen Monat gemessen wurde.",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 7 },
   "valueName": "total",
   "targets": [
    {
     "groupByAliases": [ "type" ],
     "groupByColumns": [ "entity_type" ],
     "metricAggs": [
      { "alias": "id", "column": "entity_id", "type": "raw" },
      { "alias": "value", "column": "availablespotnumber", "type": "raw" },
      { "alias": "geojson", "column": "location", "type": "raw" },
      { "alias": "created_at", "column": "time_index", "type": "raw" }
     ],
     "rawSql": "SELECT \"entity_id\", LATITUDE(\"location_centroid\") AS \"geo_lat\", LONGITUDE(\"location_centroid\") AS \"geo_long\", AVG(\"temperature\") AS \"avg_temp\" \r\nFROM \"mtsmartmaas001\".\"etweatherobserved\" \r\nWHERE WITHIN(\"location_centroid\", 'POLYGON ((9.927864074707031 54.24817702140307, 10.323028564453125 54.24817702140307, 10.323028564453125 54.43530732913595, 9.927864074707031 54.43530732913595, 9.927864074707031 54.24817702140307))') \r\nAND extract(month from \"time_index\") = extract(month from CURRENT_TIMESTAMP) \r\nAND \"temperature\" > -100 \r\nAND \"temperature\" < 50 \r\nAND \"temperature\" IS NOT NULL \r\nGROUP BY \"entity_id\", \"geo_lat\", \"geo_long\";"
    }
   ]
  },
  {
   "title": "Temperatur (°C) - Tagesverlauf",
   "type": "heatmap",
   "gridPos": { "h": 6, "w": 5, "x": 0, "y": 9 },
   "targets": [
    {
     "groupByAliases": [ "type" ],
     "groupByColumns": [ "entity_type" ],
     "metricAggs": [
      { "alias": "id", "column": "entity_id", "type": "raw" },
      { "alias": "value", "column": "availablespotnumber", "type": "raw" },
      { "alias": "geojson", "column": "location", "type": "raw" },
      { "alias": "created_at", "column": "time_index", "type": "raw" }
     ],
     "rawSql": "SELECT \"entity_id\" AS \"metric\", \"temperature\", \"time_index\" AS \"time\" \r\nFROM \"mtsmartmaas001\".\"etweatherobserved\" \r\nWHERE WITHIN(\"location_centroid\", 'POLYGON ((9.927864074707031 54.24817702140307, 10.323028564453125 54.24817702140307, 10.323028564453125 54.43530732913595, 9.927864074707031 54.43530732913595, 9.927864074707031 54.24817702140307))') \r\nAND extract(day from \"time_index\") = extract(day from CURRENT_TIMESTAMP) \r\nAND \"temperature\" > -100 \r\nAND \"temperature\" < 50 \r\nAND \"temperature\" IS NOT NULL \r\nGROUP BY \"metric\", \"temperature\", \"time\";"
    }
   ]
  },
  {
   "title": "Höchste Temperatur (°C) - Aktueller Monat",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 6, "x": 5, "y": 9 },
   "format": "celsius",
   "valueName": "avg",
   "targets": [
    {
     "groupByAliases": [ "type" ],
     "groupByColumns": [ "entity_type" ],
     "metricAggs": [
      { "alias": "id", "column": "entity_id", "type": "raw" },
      { "alias": "value", "column": "availablespotnumber", "type": "raw" },
      { "alias": "geojson", "column": "location", "type": "raw" },
      { "alias": "created_at", "column": "time_index", "type": "raw" }
     ],
     "rawSql": "SELECT \"temperature\" \r\nFROM \"mtsmartmaas001\".\"etweatherobserved\" \r\nWHERE WITHIN(\"location_centroid\", 'POLYGON ((9.927864074707031 54.24817702140307, 10.323028564453125 54.24817702140307, 10.323028564453125 54.43530732913595, 9.927864074707031 54.43530732913595, 9.927864074707031 54.24817702140307))') \r\nAND extract(month from \"time_index\") = extract(month from CURRENT_TIMESTAMP) \r\nAND \"temperature\" > -100 \r\nAND \"temperature\" < 50 \r\nAND \"temperature\" IS NOT NULL \r\nORDER BY \"temperature\" DESC limit 1;"
    }
   ]
  },
  {
   "title": "Niedrigste Temperatur (°C) - Aktueller Monat",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 5, "x": 11, "y": 9 },
   "format": "celsius",
   "valueName": "avg",
   "targets": [
    {
     "rawSql": "SELECT \"temperature\" \r\nFROM \"mtsmartmaas001\".\"etweatherobserved\" \r\nWHERE WITHIN(\"location_centroid\", 'POLYGON ((9.927864074707031 54.24817702140307, 10.323028564453125 54.24817702140307, 10.323028564453125 54.43530732913595, 9.927864074707031 54.43530732913595, 9.927864074707031 54.24817702140307))') \r\nAND extract(month from \"time_index\") = extract(month from CURRENT_TIMESTAMP) \r\nAND \"temperature\" > -100 \r\nAND \"temperature\" < 50 \r\nAND \"temperature\" IS NOT NULL \r\nORDER BY \"temperature\" ASC limit 1;"
    }
   ]
  },
  {
   "title": "Relative Luftfeuchtigkeit (%H) - Durchschnitt aktueller Monat",
   "type": "grafana-worldmap-panel",
   "description": "Der Kartenausschnitt zeigt die durchschnittliche relative Luftfeuchtigkeit (%H), die von mehreren Sensoren an unterschiedlichen Standorten im Raum Kiel im aktuellen Monat gemessen wurde.",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 14 },
   "valueName": "total",
   "targets": [
    {
     "groupByAliases": [ "type" ],
     "groupByColumns": [ "entity_type" ],
     "metricAggs": [
      { "alias": "id", "column": "entity_id", "type": "raw" },
      { "alias": "value", "column": "availablespotnumber", "type": "raw" },
      { "alias": "geojson", "column": "location", "type": "raw" },
      { "alias": "created_at", "column": "time_index", "type": "raw" }
     ],
     "rawSql": "SELECT \"entity_id\", LATITUDE(\"location_centroid\") AS \"geo_lat\", LONGITUDE(\"location_centroid\") AS \"geo_long\", AVG(CAST(\"relativehumidity\" AS float)*100) AS \"avg_relhumidity\" \r\nFROM \"mtsmartmaas001\".\"etweatherobserved\" \r\nWHERE WITHIN(\"location_centroid\", 'POLYGON ((9.927864074707031 54.24817702140307, 10.323028564453125 54.24817702140307, 10.323028564453125 54.43530732913595, 9.927864074707031 54.43530732913595, 9.927864074707031 54.24817702140307))') \r\nAND extract(month from \"time_index\") = extract(month from CURRENT_TIMESTAMP) \r\nAND \"relativehumidity\" IS NOT NULL \r\nGROUP BY \"entity_id\", \"geo_lat\", \"geo_long\";"
    }
   ]
  },
  {
   "title": "Relative Luftfeuchtigkeit (%H) - Tagesverlauf",
   "type": "heatmap",
   "gridPos": { "h": 6, "w": 5, "x": 0, "y": 15 },
   "targets": [
    {
     "groupByAliases": [ "type" ],
     "groupByColumns": [ "entity_type" ],
     "metricAggs": [
      { "alias": "id", "column": "entity_id", "type": "raw" },
      { "alias": "value", "column": "availablespotnumber", "type": "raw" },
      { "alias": "geojson", "column": "location", "type": "raw" },
      { "alias": "created_at", "column": "time_index", "type": "raw" }
     ],
     "rawSql": "SELECT \"entity_id\" AS \"metric\", CAST(\"relativehumidity\" AS float)*100 AS \"relhumidity\", \"time_index\" AS \"time\" \r\nFROM \"mtsmartmaas001\".\"etweatherobserved\" \r\nWHERE WITHIN(\"location_centroid\", 'POLYGON ((9.927864074707031 54.24817702140307, 10.323028564453125 54.24817702140307, 10.323028564453125 54.43530732913595, 9.927864074707031 54.43530732913595, 9.927864074707031 54.24817702140307))') \r\nAND extract(day from \"time_index\") = extract(day from CURRENT_TIMESTAMP) \r\nAND \"relativehumidity\" IS NOT NULL \r\nGROUP BY \"metric\", \"relhumidity\", \"time\";"
    }
   ]
  },
  {
   "title": "Relative Luftfeuchtigkeit (%H) - Durchschnitt der letzten 7 Tage",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 6, "x": 5, "y": 15 },
   "format": "humidity",
   "valueName": "avg",
   "targets": [
    {
     "rawSql": "SELECT AVG(CAST(\"relativehumidity\" AS float)*100) AS \"avg_relhumidity\" \r\nFROM \"mtsmartmaas001\".\"etweatherobserved\" \r\nWHERE WITHIN(\"location_centroid\", 'POLYGON ((9.927864074707031 54.24817702140307, 10.323028564453125 54.24817702140307, 10.323028564453125 54.43530732913595, 9.927864074707031 54.43530732913595, 9.927864074707031 54.24817702140307))') \r\nAND \"time_index\" > DATE_FORMAT(CURRENT_TIMESTAMP - 1000*60*60*24*7) \r\nAND \"relativehumidity\" IS NOT NULL;"
    }
   ]
  },
  {
   "title": "Höchste relative Luftfeuchtigkeit (%H) - Aktueller Monat",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 5, "x": 11, "y": 15 },
   "format": "humidity",
   "valueName": "avg",
   "targets": [
    {
     "rawSql": "SELECT CAST(\"relativehumidity\" AS float)*100 AS \"relhumidity\" \r\nFROM \"mtsmartmaas001\".\"etweatherobserved\" \r\nWHERE WITHIN(\"location_centroid\", 'POLYGON ((9.927864074707031 54.24817702140307, 10.323028564453125 54.24817702140307, 10.323028564453125 54.43530732913595, 9.927864074707031 54.43530732913595, 9.927864074707031 54.24817702140307))') \r\nAND extract(month from \"time_index\") = extract(month from CURRENT_TIMESTAMP) \r\nAND \"relativehumidity\" IS NOT NULL \r\nORDER BY \"relativehumidity\" DESC limit 1;"
    }
   ]
  },
  {
   "title": "Visualisierte Wetterdaten von augewählten Sensoren in Deutschland via Wirecloud Widget Mashup",
   "type": "ryantxu-ajax-panel",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 22 },
   "targets": [
    {
     "rawSql": "SELECT\n  $__time(time_column),\n  value1\nFROM\n  metric_table\nWHERE\n  $__timeFilter(time_column)\n"
    }
   ]
  }
 ]
}